### ISSUE TITLE
Redesign the website's homepage

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#106]
The website's [homepage](https://gdquest.com/) hasn't been updated in a long time and it doesn't provide a great layout and information for people visiting the website.

I'd like some complete review of the homepage's layout and content, and help to design a good one, with the key info that we should put forward.

We're a free software project, we promote programs like Krita, Blender, or Godot, and we teach game creation with free and open-source tools.

## What we do ##

- We code small [game demos](https://youtu.be/77CiZ-5JKfc) to help people learn to create games with Godot.
- We make [video tutorials](https://youtube.com/c/gdquest) and [guides](https://www.gdquest.com/docs/guides/learn-godot/beginner/) for game developers.
- We code tools to help people create games or content more easily, like the [Open 3D Mannequin](https://github.com/GDQuest/godot-3d-mannequin), the [Godot Steering Toolkit](https://github.com/GDQuest/godot-steering-toolkit/) or the Blender video editing add-on [Power Sequencer](https://github.com/GDQuest/blender-power-sequencer).

## The people who come to our website ##

Our visitors come for what we do so:

- Learning
- Getting tools and their documentation
- News about our work and projects

## What we need ##

To start with, I'd like detailed feedback and a proposal to improve or redesign the homepage's layout. I'd like somebody who's experienced with that to help us design a page that's relevant to what we do. We have a limited budget so when it comes to the website's CSS (built from scss), the proposal shouldn't require a complete rewrite of the website's styles, but rather improve, extend, or reuse the existing stylesheets. That's our main constraint.

The website is built with [hugo](https://gohugo.io/) so code-wise it's mostly HTML with a few go templates. Here's the current homepage's code: https://github.com/GDQuest/website/blob/master/layouts/index.html

## Possible redesign

Content-driven page. After the intro header that introduces the website, have two grids:

- Our latest courses
- Our latest tools/Free Software projects

And then the updates/announcements.

**Comment by gdomaradzki** [comment]
If someone provides a design, I can implement it free of charge.

**Comment by NathanLovato** [comment]
That's very kind of you! I couldn't find a designer who could do that just yet.

**Comment by NathanLovato** [comment]
In progress with  15965cf
