### ISSUE TITLE
Verify docs content

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/website#129]
We discussed that the content needs to be verified and fixed in places. For example, the beginner/developer edition Godot guides specify links to `Learn to Make Games with Godot`, but now the documents are called `Make Games with Godot: Beginner/Developer Edition`.

Minor stuff like this - tie in the content in a more cursive way, the documents were first created as entirely separate.

**Comment by NathanLovato** [comment]
I went over quite a few pages already since this issue, I think it's fine for now.
