### ISSUE TITLE
Verify layouts/shortcodes & trim unnecessary

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/website#132]
Since we started using [hugo-theme-learn](//github.com/matcornic/hugo-theme-learn/) there's an overlap in some layouts & partials. This needs to be organized a bit better. For example we have `toc.html` from hugo-theme-learn (which I overwrote so that we can have TOC for Blender Power Sequencer Reference page which is generated with a shortcode) and we also have `table-of-contents.html` which is probably used by the "main website".

There's also overlap on the CSS side.

There's the footer that we need to fix/rethink. 

Things like these.

**Comment by NathanLovato** [comment]
I went through most of the website over the past days, this is mostly done. There's always stray code left to clean up, but the bulk of it should be done.
