### ISSUE TITLE
Replace googleapi calls with more efficient method for YT playlists

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/website#133]
@NathanLovato, remember we removed the the calls to the google api, but this breaks the YT playlist pages so we need to fix this.

**Comment by NathanLovato** [comment]
I restored some of the layout, removed the outdated go templates and the API call. Got one issue though:
```
{{ range (sort ( where .Pages "Type" "video" ) "Date") }}
```
Does not return any page. I inspected `.Pages` and `.RegularPages`, which are supposed to give you a list of pages in the section, and there's only one page in the list. If I use:
```
( where .Site.RegularPages "Type" "video" )
```
I do get the entire list of video pages on the website.
