### ISSUE TITLE
Banner images don't appear in link preview on Discord

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#138]
![Screenshot from 2019-12-12 20-48-51](https://user-images.githubusercontent.com/12694995/70743821-d650cd00-1d20-11ea-8b4a-b825e42fbc5f.png)

**Comment by razcore-art** [comment]
I remember thinking about how Discord chooses the pictures to show, I just assumed it takes some image that is either singular on the page or it's used in multiple places (thumbnail to go to the article & the article itself). But I haven't looked for the actual algorithm or docs on the matter. If you have a link explaining how Discord does it, would be helpful to pinpoint the problem

**Comment by NathanLovato** [comment]
Iĺl have to check, it probably uses some webpage metadata - there's specific metadata you can use for twitter, facebook, instagram, etc to control how your content displays there.

**Comment by razcore-art** [comment]
Ref. https://css-tricks.com/essential-meta-tags-social-media/

**Comment by NathanLovato** [comment]
I found the issue, there was a condition that was outdated, so it was never creating the og:image and twitter:image meta tags
