### ISSUE TITLE
Append extra resources in writing guidelines

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/website#145]
@NathanLovato, a while ago you sent me some links on how people read and interact with web content. For some reason I can't seem to find them any more. Maybe you could link them up in the writing guidelines section as extra resources/further study or something?

**Comment by NathanLovato** [comment]
The thing I sent you was web accessibility guidelines - how to handle html interactions, color contrast etc. Except for one guideline with links (don't repeat the same link, e.g. on a picture and nearby `a` tag) they're not relevant.

**Comment by NathanLovato** [comment]
I'll find some to add at the end, e.g. for technical writing vs news posts
