### ISSUE TITLE
Split and simplify the GDScript guidelines

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#150]
We recently made some improvements to the GDScript style guide in the official docs. We could link to it and remove the parts of the guides that are all the same as the official one.  Our guidelines could be shorter and more comfortable to digest this way.

**Links**:

- [Official guidelines](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html)
- [New section on code order](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html#code-order)

Our guidelines are all in one place, and they mix a style guide and sub-articles about programming in general. We should split them into three separate pages.

## Tasks ##

- Split the [guidelines page](https://www.gdquest.com/docs/guidelines/best-practices/godot-gdscript) into several
- Simplify the articles

**Comment by NathanLovato** [comment]
@razcore-art will take care of splitting and updating the pages, as he's the original author. Once he's done, could you do a proof and editing pass, @johnnygossdev? @razcore-art you can create a branch, tell johnny when you're done, and @johnnygossdev you can directly work on that branch and add an extra commit;.

**Comment by johnnygossdev** [comment]
Sounds good to me!
