### ISSUE TITLE
Write a Getting Started guide for Power Sequencer

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#151]
See https://github.com/GDQuest/blender-power-sequencer/issues/420 for more information.

@johnnygossdev would you write that? If you can, I'll edit after you're done.

I've started writing the guide and I'm opening a branch named content/power-sequencer-getting-started where you will find the sections ready to fill up.

**Comment by johnnygossdev** [comment]
Sure! Thanks for that - I'll make a start in the next few days.
