### ISSUE TITLE
Make cards the same size

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#152]
Either use `height: 100%;` or make all banners the same size: card > img { max-height: 6em; content-fit: cover; } can give us some backward compatibility, or we could use hugo to crop the banners to the same standard size.
The cards in the tutorial section are fine: http://localhost:1313/tutorial/

**Comment by Levrault** [comment]
Using `object-fit: cover` could hide a big part of the cover

![image](https://user-images.githubusercontent.com/1162446/83131261-dd597500-a0df-11ea-8716-b4f0eb94f007.png)

vs original where we can see the krita logo

![image](https://user-images.githubusercontent.com/1162446/83131640-71c3d780-a0e0-11ea-89dc-5031298bee59.png)

For this test, I set a normalize height of 290px on desktop, I resize to 100% on mobile. If hide a part of the cover doesn't border you, it could be a solution.

**Comment by NathanLovato** [comment]
the object-fit: cover option seems to work well. We're going to have new banners moving forward and keep updating the layout so it should become more and more consistent, hopefully.
