### ISSUE TITLE
Icons and links in the main navigation don't react to hover or input

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#156]

**Comment by gdomaradzki** [comment]
Is there any guidelines for the hover effects?

**Comment by NathanLovato** [comment]
I think this would need some general thoughts, in conjunction with #155. Right now buttons are just an outline with dark text inside by default. On hover, they fill up with their outline color and the text fades to white.

But if the buttons were filled by default, the hover state would have to be different, and more consistent with the rest of the website.

For the icons, as they're white, I'd try fading them to the primary color of the website - blue. Same for the links in the main nav. 

Two quick tests:

![Screenshot from 2020-02-12 08-58-58](https://user-images.githubusercontent.com/12694995/74347010-0d217e80-4d76-11ea-93a5-71f14e6cc605.png)

![Screenshot from 2020-02-12 08-59-40](https://user-images.githubusercontent.com/12694995/74347022-114d9c00-4d76-11ea-8c17-f294f17a236a.png)

**Comment by NathanLovato** [comment]
Closed in 4293e5b27fcd4c0f92dd30a87f595e5b5978838c and ea4215a9e4cb4e4634d268561ff79836c925771c
