### ISSUE TITLE
Write simple art design styleguide GDQuest gamedev demos

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#157]
Write a short style guide with example assets for our demos. We'll use it as a base to create appealing tutorials and demos, and for our contributions to the official godot demos repository.
Use the beginner 2D platformer as a base: https://github.com/GDQuest/godot-beginner-2d-platformer

The goals for this task are:

- To produce a simple document, mostly visual in nature. Use pictures (SVGs will work great) over long paragraphs, link to resources like color palettes.
- To develop an art style that doesn't take a lot of work but still looks good. 

Write some guidelines for shapes and colors: what do we use for walls, to signal dangers, etc?
The art style should give us great readability and clarity.

**Comment by NathanLovato** [comment]
Aim for less than 800 words, that should be more than enough for this. With good pictures, you can get away with way fewer even.

Also if you use SVGs, you will need to export them for the web from inkscape - not all SVG features inkscape uses are supported by web browsers.

**Comment by henriiquecampos** [comment]
So I started first by creating some mockups to test the design before writing it down and get some feedback for improvements.

The idea is to standardize some core aspects:

- What represent players
- What represent enemies
- How to represent dangers
- A theme for game UI 
- A theme for off game UI (i.e. debug)

So here are some use cases:

# Main Menu

![main-screen](https://user-images.githubusercontent.com/10171059/73539730-da3dc900-440c-11ea-8d7a-5e6ec136ca85.png)

## Some more UI elements

![options-screen](https://user-images.githubusercontent.com/10171059/73539739-e2960400-440c-11ea-97ab-23380139afcd.png)

# A platformer

![platformer](https://user-images.githubusercontent.com/10171059/73539558-669bbc00-440c-11ea-9613-8b241bd241d8.png)

# Topdown shooter/space shooter/RTS

![topdown-shooter](https://user-images.githubusercontent.com/10171059/73539579-75826e80-440c-11ea-80bd-f56cb6a4723f.png)

![topdown-no-lines](https://user-images.githubusercontent.com/10171059/73539600-8632e480-440c-11ea-9360-6bf22f4971c6.png)

## With Debug panel

![debug-panel](https://user-images.githubusercontent.com/10171059/73539630-9c40a500-440c-11ea-9ff6-550aa9324f8c.png)

# Topdown adventure

![topdown-nolines2](https://user-images.githubusercontent.com/10171059/73539678-b8dcdd00-440c-11ea-8e18-a217c358bac7.png)

# Ingame Debug console

![debug-console](https://user-images.githubusercontent.com/10171059/73539781-00fbff80-440d-11ea-94f4-377da42dab8f.png)

# Ingame Menus (dimmed)

![topdown-shooter-paused](https://user-images.githubusercontent.com/10171059/73539809-0f4a1b80-440d-11ea-8f24-3c412364adec.png)

# Some Debug elements

![topdown-debug](https://user-images.githubusercontent.com/10171059/73540338-67cde880-440e-11ea-884a-9d2114dc6670.png)

![topdown-debug2](https://user-images.githubusercontent.com/10171059/73540775-8e405380-440f-11ea-9bba-8c8dc96dcd28.png)

**Comment by NathanLovato** [comment]
Looking good overall. Here's some feedback

## Debug UI doesn't belong here ##

Debug panels and UIs fall outside of this task to me.

Debug UIs are tools for developers, so they should be designed to:

1. Display potentially a lot of technical information.
2. Overlay on top of the game world, as you use them to get info about or interact with the running game.
3. Be clearly distinguished from the game world, visually-speaking, as they're not part of it, unlike the game UI.
4. Have the text align precisely, as in a code editor. A small monospace font is more appropriate for something like that.

You're likely to display more than a few lines and e.g., in an in-game console, print entire streams of data. For debug tools, I also prefer to have a generic, non-intrusive UI, with an optional transparent background, so you can see the game running and changing through the panels. Imgui can be a great example of that.

Anyway, we already have a separate project for that: https://github.com/GDQuest/godot-gdquest-theme/.

_On a side-note, I was also thinking we could piggyback on the editor theme instead of designing our own completely - having something consistent with Godot rather than trying to have something "GDQuesty", tweaking the UI where appropriate (e.g. supporting transparent backgrounds)._

However, elements that are inside the game world, like the path you're showing, it makes sense for them to follow the same style. You can consider them as game elements - like in an RTS game, you can see the movement path or target actions of selected units.

## The game UI looks blocky at the moment ##

For the game UI, I'd try without the outlines. It looks blocky at the moment, and the stroke around the pause menu buttons make the text look misaligned, due to the difference in distance between the bounds of the text and the stroke (with the tail of the Q and p in Quit and Options). Buttons without outlines would attenuate that.

## The scale of the graphics is good for mobile, big for desktop ##

I also find the scale a little too mobile-like at the moment. While it'd work great on a 5" mobile display, on my 16" laptop display, right now, the graphics are really in my face. And that's where people are mostly going to run the demos.

That's a detail that's easy to fix, including in-game (changing the camera zoom), but I think the visuals would look richer with more elements and using a smaller size for each of them.

We can have different scales for mobile and desktop demos respectively. Actually, it'd be nice to have a mobile portrait example, as Godot is also a tool to dev mobile games.

**Comment by henriiquecampos** [comment]
> Debug UIs are tools for developers

I thought of them more like teaching tools to show technical runtime information to the viewer.

I've applied some changes especially to the elements' size allowing to display more elements as suggested.

# Topdown Adventure

![topdown-adventure-highres](https://user-images.githubusercontent.com/10171059/73549904-4d9e0580-4422-11ea-9c77-3cfbaded4356.png)

# Platformer

I've used some reference like Ori and Hollow Knight to get an idea of the elements' size, especially the floor base size and the character's size.

![platformer-highres](https://user-images.githubusercontent.com/10171059/73549927-60b0d580-4422-11ea-9cd4-653b20867fc5.png)

# Topdown shooter

![topdown-shooter-new](https://user-images.githubusercontent.com/10171059/73550533-85f21380-4423-11ea-8ac6-2a60f8a56503.png)

# The UI

![new-ui](https://user-images.githubusercontent.com/10171059/73550748-eaad6e00-4423-11ea-888a-2d5571ce6af3.png)

![new-ui-elements](https://user-images.githubusercontent.com/10171059/73550760-ee40f500-4423-11ea-8463-45dcdf574cd8.png)

# Transparent console

![new-debug-console](https://user-images.githubusercontent.com/10171059/73550788-fbf67a80-4423-11ea-84ec-a87ed42090e4.png)

# Monospace debug panel

![new-debug-panel](https://user-images.githubusercontent.com/10171059/73550831-129cd180-4424-11ea-956a-e9c6dd01945f.png)

# Some Portrait mockups

![portrair-topdown-adventure](https://user-images.githubusercontent.com/10171059/73551356-082f0780-4425-11ea-80b4-475c52bde652.png)
![portrait-platformer](https://user-images.githubusercontent.com/10171059/73551357-082f0780-4425-11ea-941c-769336b45377.png)
![portrait-topdown-shooter](https://user-images.githubusercontent.com/10171059/73551358-082f0780-4425-11ea-9b7f-bbe963976c73.png)

**Comment by NathanLovato** [comment]
Looking great to me, you can move forward!
