### ISSUE TITLE
Rename mannequiny.png to screenshot.png

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/website#159]
Currently, in /content/post/2020/01/mannequiny-released, index.md has been changed to refer to screenshot.png, but the image mannequiny.png was not renamed accordingly, which results in a broken image in the news post.

I've pushed a commit on master to fix it, but I think it needs a rebuild.

**Comment by NathanLovato** [comment]
The website always rebuilds automatically.

**Comment by NathanLovato** [comment]
Actually the image path was correct, I overwrote and compressed your picture, had just forgotten to stage it in the commit. I'll fix that now.
