### ISSUE TITLE
Use the RSCSS style guide for CSS and HTML

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#166]
Our CSS and layouts aren't too clean and comfortable to maintain. We haven't used a style guide until now, so every time we've changed them, the style got mixed a bit more.

I'd like to use the RSCSS style guide throughout our codebase: https://rscss.io/ 

RSCSS is like the BEM style, but with more natural code to me. In short, you break your website and UI into a library of components that have elements and variants. Components can be things like a menu, a button, a search bar.

Here's a comparison between bem and rscss syntax:

```html
<!-- BEM -->
<form class='site-search site-search--full'>
  <input  class='site-search__field' type='text'>
  <button class='site-search__button'></button>
</form>

<!-- rscss -->
<form class='site-search -full'>
  <input  class='field' type='text'>
  <button class='button'></button>
</form>
```

This task involves quite a bit of refactoring, so it's going to be an ongoing job.

**Comment by gdomaradzki** [comment]
Maybe it would be a good idea to postpone this major refactor until a new design is ready? What are your opinions?

**Comment by NathanLovato** [comment]
There's no major redesign of the website planned for now, only incremental changes. I would do this gradually and take it as an opportunity to review the website's design. The reason is that if we don't do it, we're going to accumulate tech debt. I checked the css the other day and it's mixed, a little all over the place, and that is already after a trimming and refactoring pass from me months, maybe one year ago.

**Comment by gdomaradzki** [comment]
I will try to tackle this tomorrow, then.

**Comment by NathanLovato** [comment]
The bulk of the task is done, although there are some stray classes and styles left. Especially for layout. For the remaining work, we'll refactor as we need to change the website's source code.
