### ISSUE TITLE
Docs navigation is not working properly

### ISSUE THREAD

**Issue by hectormartinezdev** [GDQuest/website#169]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When you go to "Guidelines" on the docs "/docs/guidelines" or other pages, the right button "next page" always go to "docs/guides/learn-godot/".

**What is the expected behavior?**
To go the next page in the tree view.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Go to https://www.gdquest.com/docs/guidelines/
2. Press the right "next page" button

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information** 

I think that the content tree is not build correctly or that the navigation is hardcoded in some way.

**Comment by NathanLovato** [comment]
Thanks. The navigation isn't hard-coded, and it used to work, so it might be the content or something. I'll add it to my todo list for today.
