### ISSUE TITLE
Add a partial that lists the latest tutorials

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#198]
We need a way for people to see the latest tutorials and maybe when they were added. This could be on the tutorial section page, or accessible in tutorial sub-sections.

**Comment by NikolaSiplakova** [comment]
Hi, could you assign me this task, please? :)

**Comment by NathanLovato** [comment]
Thanks. A note regarding the issue: it's about adding a partial file that automatically lists the latest X tutorials, such that it updates automatically when we add new tutorials to the website. Also, style-wise, considering we don't have banners or nice pictures for most tutorials, I'd recommend using a bullet list, maybe with some pills based on the tutorial's metadata (difficulty level, video or text)

**Comment by NathanLovato** [comment]
Hi @NikolaSiplakova, are you still on this? I'm gonna work on the website this week and would like to add this long overdue improvement.
