### ISSUE TITLE
Multilingual support: adapt the language-dropdown to mobile

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#231]
The dropdown currently only works on desktop, it's hidden in the mobile menu. See language-dropdown.html and .scss

**Comment by NileshChoudhary111** [comment]
Hi Nathan,

Could you please provide some more information on this, any screenshot would help me to check and get it fixed ASAP?
Thank you.

**Comment by NathanLovato** [comment]
This menu is set to `display: none;` on mobile devices. See language-dropdown.scss for the source code.

![Screenshot from 2020-10-24 08-12-53](https://user-images.githubusercontent.com/12694995/97083934-c6f11000-15d0-11eb-8158-2ba05221097e.png)

It needs some scss code to display well on mobile inside the menu.

![Screenshot from 2020-10-24 08-15-16](https://user-images.githubusercontent.com/12694995/97084000-1cc5b800-15d1-11eb-89c0-33ea20a14d0f.png)

See nav-main.scss for the social menu's links.

**Comment by Calinou** [comment]
I'm working on this, stay tuned :slightly_smiling_face:
