### ISSUE TITLE
Add netlifycms

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#239]
A CMS would make it easier for new writers to work on the  website. We use netlify and their cms works with GitHub.

Install guide: https://www.netlifycms.org/docs/add-to-your-site/

We should use the editorial workflow as we peer review and edit every article.

@Calinou would you like to tackle it or should I?

**Comment by Calinou** [comment]
I have no experience with Netlify, so I'm afraid I can't be of much help here.

**Comment by NathanLovato** [comment]
I'm on it then!
