### ISSUE TITLE
In the Finite State Machine article, an error in the code

### ISSUE THREAD

**Issue by lstep** [GDQuest/website#246]
In the `STATE VARIABLE`, you wrote:
```python
[...]
# Canceling gliding.
if _state == States.GLIDING and Input.is_action_just_pressed("jump"):
	_state == States.GLIDING = States.IN_AIR
[...]
```
The last line is not possible (and generates an error in Godot, which is normal :-) ), it should be an assignment, not a boolean test, but an asignment of what, I don't know...

**Comment by NathanLovato** [comment]
Thanks, William also mentioned this on Twitter. I wrote the code without testing it, directly in the markdown doc, as it was meant almost like a pseudo-code example. But I should create a working demo for it in [Godot design patterns](https://github.com/GDQuest/godot-design-patterns)

I logged a task to add the code to the repo and fix it in the article.

**Comment by NathanLovato** [comment]
Already fixed by a previous update.
