### ISSUE TITLE
Some code could be made easier to read 

### ISSUE THREAD

**Issue by Feniks-Gaming** [GDQuest/website#251]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Feature request ##

This is feature request for States turorial

In current version some parts of code are not very easy to follow

```
func _physics_process(delta: float) -> void:
	#...
	# Instead of using different functions and variables, we can now use a single variable 
	# to manage the current state.
	var is_jumping: bool = _state == States.ON_GROUND and Input.is_action_just_pressed("move_up")
```

I feel that 

`var is_jumping: bool = _state == States.ON_GROUND and Input.is_action_just_pressed("move_up")`

could be broken down into 2 lines of code for readability sake. It took me a while to figure out what is happening here. Much easier solution to this would be changing it into 

```
If _state == States.ON_GROUND and Input.is_action_just_pressed("move_up"):
    var is_jumping: bool = true
else:
    var is_jumping = false
```

I know it's more lines of code but cramming this thing into one line was really confusing.

**Comment by NathanLovato** [comment]
I would prefer people to learn to read and understand boolean expressions, and in particular, that they don't require conditional branches.

I can imagine this was confusing for you if you're not used to seeing lines like these, but at the same time your if statement does the same thing: it evaluates the condition, and if it evaluates to `true`, it sets the variable to `true`, but if it evaluates to `false`, it assigns `false` to the variable.

Anything you put after "if" or "elif" has to be a boolean expression, which always evaluates to `true` or `false`.

Once you make that idea yours, you'll understand every variable assignment that includes `==`, `and`, `or`, and all the other comparison operators. It's an expression that always evaluates to either `true` or `false`.

**Comment by NathanLovato** [comment]
I'll add that above, the point of the variable is to make the boolean expression explicit: the character `is_jumping` when the state is equal to `States.ON_GROUND` and the player just pressed `move_up`.

**Comment by Feniks-Gaming** [comment]
Yeah I understand what was a reason behind it maybe comment explaining what it does will help. I understood this line of code it just took more energy than understanding few seperate lines.

**Comment by NathanLovato** [comment]
Regarding the issue you opened, was there anything other that this line of code?

**Comment by Feniks-Gaming** [comment]
No it's fine from what I have seen with the rest happy for it to be closed.

**Comment by NathanLovato** [comment]
Okay, don't hesitate to open issues whenever you see something like this. Also you should find a button at the bottom of every tutorial to modify it, and you can use the github text editor to do so. It's markdown so it's simpler than the Godot docs.

**Comment by Feniks-Gaming** [comment]
Thanks will give it a go.
