### ISSUE TITLE
Remove Gumroad courses /product page.

### ISSUE THREAD

**Issue by Razoric480** [GDQuest/website#274]
Make professional 2D Games with Godot, Make cel shaded 2D Characters with Krita, Create User Interface in Godot, and Make Professional Painterly Game Art with Krita are still being advertised on the /Product page, but following through shows a 'not available for sale' button.

**Comment by NathanLovato** [comment]
Fixed, thanks for the heads up 0c80572bfdcd68b0ea9797d5c1c8c0613a9b087d
