### ISSUE TITLE
Feedback/Contact typo

### ISSUE THREAD

**Issue by TheYellowArchitect** [GDQuest/website#281]
Was reading the great tutorials and want to give feedback on a minor typo I noticed. On the bottom section of each page where a user sends feedback/question, it says: "We encrypt your addres with a strong 256-bit AES encryption."

The typo is in address (its kinda bad when its related to security/trust lol)

**Comment by NathanLovato** [comment]
Thanks for the report. We removed the comments since this issue was opened so the message isn't present anymore.
