### ISSUE TITLE
Broken links on the GDQuest website

### ISSUE THREAD

**Issue by PaulArgent** [GDQuest/website#285]
**I'm submitting a...**

- [x] Bug report.

## Bug report ##
Hi! I found a few broken links on the GDQuest website:

- [x] 1. [Mobile Game: Circle Jump](https://kidscancode.org/godot_recipes/games/circle_jump/) link on the [beginner](https://www.gdquest.com/tutorial/godot/learning-paths/beginner/) page is broken.
New right link: [Mobile Game: Circle Jump](https://kidscancode.org/godot_recipes/3.x/games/circle_jump/)
- [x] 2. [Godot game engine](https://www.gdquest.com/godotengine.org/) link on the [developer](https://www.gdquest.com/tutorial/godot/learning-paths/developer/) page is broken 🙃.
- [x] 3. [Godot Shaders playlist](https://www.youtube.com/playlist?list=PL9NDikg3iIaXtGQY6HIgzUxfuMTkybzyx) link on the [developer](https://www.gdquest.com/tutorial/godot/learning-paths/developer/) page is empty.
- [x] 4. [Procedural Content Generation in Games](http://pcgbook.com/) link on the [developer](https://www.gdquest.com/tutorial/godot/learning-paths/developer/) page is unavailable. Perhaps temporarily?
- [x] 5. [NotGDC](http://www.notgdc.fun/) link on the [developer](https://www.gdquest.com/tutorial/godot/learning-paths/developer/) page is unavailable.

**Comment by NathanLovato** [comment]
Thanks, don't hesitate to make a PR to fix these, otherwise I'll look at this after the Godot 4.0 release crunch
