### ISSUE TITLE
Change signals to new connect() syntax

### ISSUE THREAD

**Issue by Scroogeee** [GDQuest/website#291]
**I'm submitting a...**

- [ ] Bug report.
- [x] Feature request.

## Feature request ##

**Describe the problem you're trying to solve.**
Godot seems to have a new syntax for working with signals which doesn't rely so much on strings anymore, as detailed in this documentation page: https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html

I would like to learn about that new system too.

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**
Possible solutions would include simply adding an explanatory text box telling people about the new system. (less work)
Alternatively the whole tutorial page could be rewritten with the new syntax and the video could be adjusted. (more work)

**Comment by NathanLovato** [comment]
Every tutorial on the website is for Godot 3.5 and, as such, is going to be archived once we release our new, upcoming web platform. We're preparing new content for Godot 4 and we don't plan to just port existing, old, sometimes lower quality content to Godot 4.
