### ISSUE TITLE
Third person controller

### ISSUE THREAD

**Issue by Alienhead-dev** [GDQuest/website#302]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

**What is the expected behavior?**

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by Alienhead-dev** [comment]
Would be extremely helpful if this project would load up and run with the latest godot version. 
I gave up on it with all the conversions and shit godot was trying to do to the project. BTW it wouldnt even run so I found this a huge waste of my time.

**Comment by NathanLovato** [comment]
This third person demo runs in Godot 4.2: https://github.com/gdquest-demos/godot-4-3d-third-person-controller/
