### ISSUE TITLE
Add support for translations

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#44]
The static engine behind the website, hugo, supports [translations](https://gohugo.io/content-management/multilingual/).

There's just a few tasks to get started:

- [ ] translate one piece of content
- [ ] add a i18n partial to list available languages for a given article, e.g. in a drop-down menu
- [ ] add translations for some base parameters like languages etc. maybe?

If anyone wants to translate a tutorial, send me a message and I'll work on this.

**Comment by Greaby** [comment]
Hello, I am interested in helping to translate the tutorials into French.

**Comment by NathanLovato** [comment]
Thanks! You can already get started: all we need is to copy a file and instead of naming it `name.md`, call it `name.fr.md`. Here's an example in `content/about/`:

![Screenshot from 2020-10-21 10-42-08](https://user-images.githubusercontent.com/12694995/96751166-18f42480-138a-11eb-9929-617b0a62de99.png)

I'll write some instructions on the README.
