### ISSUE TITLE
Review the guide to contribute to gdquest's projects

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#84]
Review the [guide](https://www.gdquest.com/open-source/guidelines/contributing-to-gdquest-projects/) and list everything that:

- Needs to be clarified or improved
- Is missing and should be explained

Especially things related to the git workflow, working together with a growing team and more contributors in the future.Having everyone make sure that their peers are great.

I need quick notes and feedback, like a bullet list of improvements to make.

**Comment by NathanLovato** [comment]
Notes by @razcore-art :

# Contributing to GDquest's projects

## consistency throughout the website

- eg. make sure everywhere we have `GDquest` and not `GDQuest` or other forms, I found it here and there

## needs to be clarified

Apart from practical examples of `git` workflow, so something like showing how to commit specific changes to be integrated in the project, after the squash I haven't seen any need to expand on any specific sections.

- in *WRITING A GREAT BUG REPORT* specify git version/hash of program if using CI (continuous integration) build or some other form of build directly from git repository

## is missing

- *HOW TO CREATE GREAT PULL REQUESTS* should include a short intro/description just like *HOW TO WRITE GREAT BUG REPORTS AND REQUESTS*
- I'm not sure how to tackle this (easily) but I'd say including a discussion about *HOW TO GET STARTED WITH OPEN SOURCE PROJECTS* is needed, things that we discussed over at discord, how to find things in the source code, how not to get overwhelmed, how to find specific modules/parts of the project one is interested in and how to go about learning these parts of the code
- In the context of a growing team, work models - benevolent dictator, decentralized workflow etc. with given non-overlapping tasks, if there's people to be assigned to specific issues/projects/tasks
- *edit*: after writing this I realized that a subchapter could be on WIP PRs/branches which isn't discussed yet

An unspoken rule when starting new book chapters is that each chapter should include a short summary/intro and should never go into subchapters directly which is what the above 1st point is about.


# GDquest's Kind Communication Guidelines

There's this idea of sandwiching the critique like this:

  1. positive opening remarks 
  1. constructive critique 
  1. positive closing remarks

  - best to include example critiques

**Comment by razcore-art** [comment]
I was going through my notes and seeing you close the issue on `1 day jams`: GDquest/godot-metroidvania-2d#44, there's some good things in there that we could expand on:

- have a small discussion on how living in different time zones impacts development, you're probably well equipped to write about it
- having a team with specific tasks, like I'm in charge of keeping the code up to the standards our guidelines (lead dev and all) so it makes sense to have a loose workflow at times, eg. during push-phases/jams
- push design first & refine later
- getting priorities right

**on communication**:
- can give examples of failed/bad communication to draw conclusions from it, eg.:

NathanLovato's comment:
> For instance, Razvan added a dash skill as an unlockable skill. That's typically the kind of design ideas I'm not interested in: the hook can do what a dash offers and more, better. If the hook failed to provide this ability, it would mean we should improve the hook rather than add a new control and a new move.
> It was just an example to test code architecture in this case, no big deal. But before adding a new move or mechanic, please ask.
